<?php
/**
 * Created by PhpStorm.
 * User: gaobin
 * Date: 2019/1/5
 * Time: 11:49 AM
 */

namespace app\index\common\controller;


use app\admin\modle\Web;
use app\index\model\Categorys;
use think\Controller;
use think\facade\Request;
use think\facade\Session;

class Base extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->navShow();
        $this->is_open();
    }

    //防止登录
    public function isLogin()
    {
        if (Session::has('uid')){
            return $this->error('客官,您已经登录','index/index');
        }
    }

    // 防止注册
    public function isRegister()
    {
        if (Session::has('uid')){
            return $this->error('客官,您再登录状态，不能注册','index/index');
        }
    }
    //没有登录就不能发布文章
    //防止登录
    public function isArticle()
    {
        if (!Session::has('uid')){
            return $this->error('客官,您没有登录,不能发布文章','/login');
        }
    }

    //显示nav 导航分类
    public function navShow()
    {
        //得到栏目数据
        $categorys = Categorys::all(
            function ($query){
                $query->where('status',1)->order('sort','asc');
            });
        return $categorys;
    }

    //检测站点是否已关闭:在公共控制器初始化方法中调用
    public function is_open()
    {
        //1.获取当前站点的状态
        $isOpen = Web::where('id',1)->value('is_open');

        //2.如果站点是关闭状态,那我们只允许关闭前台模块,后台模块必须仍然可以访问
        if ($isOpen == 0 && Request::module() == 'index'){
            //或者写上:此域名出售
            $info = <<<'INFO'
            <body style="background-color:#333">
            <h1 style="color:#eee;text-align:center;margin:200px">站点维护中...</h1>
            </body>
INFO;
            exit($info);
        }
    }

    public function is_reg()
    {
        //1.获取当前站点的注册状态
        $isReg = Web::where('id',1)->value('is_users');

        //3. 如果已关闭注册,则直接跳转到首页
        if ($isReg == 0) {

            $this->error('注册已关闭','index/index');
        }
    }
}